name        = "Hot Chocolate"
license     = "MIT"
licenselink = "https://github.com/andrewjesaitis/hot-chocolate/blob/master/LICENSE"
description = "Consistent, responsive theme with clean typography"
homepage    = "https://github.com/andrewjesaitis/hot-chocolate/"
tags        = ["open-sans", "minimal", "clean", "svg", "comments"]
features    = ["blog", "responsive", "404", "icons", "disqus", "metadata"]
min_version = 0.18

[author]
  name      = "Andrew Jesaitis"
  homepage  = "https://github.com/andrewjesaitis"
